spring.devtools.restart.enabled=false
server.servlet.context-path=/
server.port = 8080

spring.config.import=classpath:globals.properties

spring.datasource.driver-class-name=${Globals.DriverClassName}
spring.datasource.url=${Globals.Url}
spring.datasource.username=${Globals.UserName}
spring.datasource.password=${Globals.Password}

# mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# MyBatis
#mybatis.config-location=classpath:egovframework/mapper/config/mapper-config.xml

# Mapper XML
mybatis.mapper-locations=classpath:egovframework/**/mapper/*.xml
mybatis.type-aliases-package=egovframework.com.ites.**.service

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# error
server.error.whitelabel.enabled=false
