spring.devtools.restart.enabled=false
server.servlet.context-path=/
server.port = 8080

spring.config.import=classpath:globals.properties

spring.datasource.driver-class-name=${Globals.DriverClassName}
spring.datasource.url=${Globals.Url}
spring.datasource.username=${Globals.UserName}
spring.datasource.password=${Globals.Password}

# MyBatis 기본 설정 파일
mybatis.config-location=classpath:egovframework/mapper/config/mapper-config.xml

# Mapper XML 위치
mybatis.mapper-locations=classpath:mapper/**/*.xml

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
